version: 2

sphinx:
  configuration: docs/confg.py

formats: all

build:
  image: latest

python:
  version: 3.6
  install:
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .
