language: python
python:
- 3.6
install:
- pip install pytest pytest-mock
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: vivarium
  password:
    secure: ovm+O/Rv6XfkDl24NLntd/KA/PzGG6+jTHb5NyS7RfEQMz+wYGkPpmUQmOh7w/qHPNob/Gls3wBJKhR9hclLCk5tMjfj2MfaQA+EyG7fZjmSYQ0cVkkirn+omMY11eY0oHRkyjlxYgP8/WcNnYZb8koFWA/jizDQt+F/PBHc/6M0xiAQg0ZFE3R3VpMKxG8PNzNvn0ADcKO90+ok0SF77pK+C6qHPVcZMuyrqzN3Dq7kJP+ra5ZE3bCw9EMZhYeHbYHbK/gSK2CZwM3p/wcfN6fcIUQajzScwV8jthiHUR9qjQoRJRGB0H1K0bo57VQoGVZAEi0F9qmL/oW+5Gi8tmcxloXV+HyttmF8SqEAjxaf0yzMRHr30i6EbzSDXTeT5dPjxjee/KVVeOzREQAWj9Oii5jgJXtUlmXU7B+cZfSiZ4kekyGzxjO5BFvk3RA7QunntluaE3fk2ars7KwWOpo9WPmstZNYo4HT6jjZVte+YsdjjjnECzGfJ88lLXI6TYwf2u6hgrPnWE2/ShSQUYsqDXGlnFaXnNOcqnD9SFDIe2hF6FfbToTnDa2fLwW8rHFjypgD7EZsGuMbznocfK4p3FV46UUrflUO1eLWn+GddEsqNXjzOZSDqK6ATex++8NTjZkrWGC5spVjKtnGcjiEYFJNKd22qdjeZrRIiBk=
  on:
    distributions: sdist bdist_wheel
    repo: ihmeuw/vivarium_cluster_tools
    tags: true
